### ISSUE TITLE
Has anyone managed to find / resurrect a MDL runtime to actually make this go?

### ISSUE THREAD

**Issue by feoh** [itafroma/zork-mdl#1]
Given how well ITS has been emulated these days I thought it might be possible....

**Comment by itafroma** [comment]
[Matthew Russotto](http://www.russotto.net) created an MDL interpreter called [Confusion](http://www.russotto.net/git/mrussotto/confusion) that, as [he claims](http://www.russotto.net/git/mrussotto/confusion/src/master/src/README), "works just well enough to play the original Zork all the way through." I have not tried to build or run it: I've mostly been interested in the language itself. Should be interesting if it still works!

None of the original runtimes exist as far as I know. There was [an attempt last year](https://github.com/PDP-10/its/issues/12) to find them, which appeared to turn up fruitless for now.

**Comment by larsbrinkhoff** [comment]
There is now an MDL runtime that @atsampson backported to ITS.
